- id: '1738044081884'
  alias: Button Ambiance
  description: ''
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 4
    unique_id: 26c06448-35e3-4a33-9dbd-f29011f3da42
    metadata: {}
    trigger: device
  - trigger: time
    at: '19:30:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_ambiance
  mode: single
- id: c17468b6-dd40-11ef-8c63-00155d918f67
  alias: Bedside Light Toggle
  description: ''
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 1
    unique_id: c5bc7b4c-a04e-4248-8ec7-de20c3ca926b
    trigger: device
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 17ede8441b0d96619f9255122894377f
    entity_id: e273724e036742495ef4a2ebe8655158
    domain: light
  mode: single
- id: 18fff798-dd42-11ef-8bc4-00155d918f67
  alias: Activate Office Concentrate
  description: ''
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 2
    unique_id: 82b3a93d-b368-42ef-bc4b-898601770261
    trigger: device
  - trigger: time
    at: 07:15:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_natural_light_2
  mode: single
- id: 7b30dd06-dd42-11ef-afa0-00155d918f67
  alias: Toggle Office Light
  description: ''
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: repeat
    subtype: 2
    unique_id: 82b3a93d-b368-42ef-bc4b-898601770261
    trigger: device
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: long_press
    subtype: 2
    unique_id: 82b3a93d-b368-42ef-bc4b-898601770261
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.office_2
  mode: single
- id: '1733544795405'
  alias: Good evening murder
  description: ''
  triggers:
  - trigger: time
    at: '20:15:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.bedroom_murder_2
  mode: single
- id: '1762138711858'
  alias: git pull on commit
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.raypappa_home_assistant_latest_commit
  conditions: []
  actions:
  - action: shell_command.git_pull
    metadata: {}
    data: {}
  mode: single
- id: '1762140408973'
  alias: shower temp delay
  description: ''
  triggers:
  - device_id: 7230294486277129ba36ae06eee4748a
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: script.pre_heat_bathroom_2
    metadata: {}
    data: {}
  mode: single
- id: '1762141277519'
  alias: Good Morning wakeup weekday
  description: ''
  triggers:
  - trigger: time
    at: 06:15:00
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
- id: '1762649853399'
  alias: Good morning weekenend
  description: ''
  triggers:
  - trigger: time
    at: 09:00:00
  conditions:
  - condition: time
    weekday:
    - sun
    - sat
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 1
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
- id: '1763190360771'
  alias: update public dns
  description: ''
  triggers:
  - trigger: time
    at: 05:00:00
  conditions: []
  actions:
  - action: route53.update_records
    metadata: {}
    data: {}
  mode: single
- id: '1763956557659'
  alias: Office get off work
  description: ''
  triggers:
  - trigger: time
    at: '17:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_relax_3
  mode: single
- id: '1764409455897'
  alias: Toggle bedroom fan light
  description: ''
  triggers:
  - device_id: f52a8b458b663be3829316c8e1a3ecae
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_double_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: f18892c9ee2f699cd8dbd0db78535e67
    entity_id: c017269a327e304ac102af10e5feecfa
    domain: light
  mode: single
- id: '1766370415952'
  alias: Periodic AlwaysOn check
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '*'
    minutes: '15'
    seconds: '0'
  conditions: []
  actions:
  - action: script.turn_on_alwayson_devices
    metadata: {}
    data: {}
  mode: single
- id: '1766653260333'
  alias: Enable good morning weekday
  description: ''
  triggers:
  - trigger: time
    at: '10:00:00'
  conditions: []
  actions:
  - action: automation.turn_on
    metadata: {}
    target:
      entity_id:
      - automation.good_morning_wakeup_weekday
      - automation.good_evening_murder
    data: {}
  mode: single
