- id: '1738044081884'
  alias: Button Ambiance
  description: ''
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 4
    unique_id: 26c06448-35e3-4a33-9dbd-f29011f3da42
    metadata: {}
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_ambiancee
  mode: single
- id: c17468b6-dd40-11ef-8c63-00155d918f67
  description: ''
  mode: single
  alias: Bedside Light Toggle
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 1
    unique_id: c5bc7b4c-a04e-4248-8ec7-de20c3ca926b
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 17ede8441b0d96619f9255122894377f
    entity_id: e273724e036742495ef4a2ebe8655158
    domain: light
- id: 18fff798-dd42-11ef-8bc4-00155d918f67
  alias: Activate Office Concentrate
  description: ''
  mode: single
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: initial_press
    subtype: 2
    unique_id: 82b3a93d-b368-42ef-bc4b-898601770261
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_concentrate
- id: 7b30dd06-dd42-11ef-afa0-00155d918f67
  alias: Toggle Office Light
  description: ''
  mode: single
  triggers:
  - device_id: 7361c462858d897c2c65cc574e057b81
    domain: hue
    type: repeat
    subtype: 2
    unique_id: 82b3a93d-b368-42ef-bc4b-898601770261
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.office_2
- id: '1734221551039'
  alias: Power Outage Shutdown services
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.myups_battery_charge
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: 20
  conditions:
  - condition: state
    entity_id: sensor.myups_status
    state: On Battery Battery Discharging
    for:
      hours: 0
      minutes: 5
      seconds: 0
  actions:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.poweredge_r540_power_off_poweredge_r540
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: shutdown_return
    device_id: 330d62354c250d1600ba0765efe10d0c
    domain: nut
  mode: single
- id: '1733544795405'
  alias: Good evening murder
  description: ''
  triggers:
  - trigger: time
    at: '20:15:00'
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.bedroom_murder
  mode: single
- id: '1761103490410'
  alias: Toggle bedside light
  description: ''
  triggers:
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 17ede8441b0d96619f9255122894377f
    entity_id: e273724e036742495ef4a2ebe8655158
    domain: light
  mode: single
- id: '1762138711858'
  alias: git pull on commit
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.raypappa_home_assistant_latest_commit
  conditions: []
  actions:
  - action: shell_command.git_pull
    metadata: {}
    data: {}
  mode: single
- id: '1762139700483'
  alias: toggle bedside light button
  description: ''
  triggers:
  - device_id: 82ac3d5614908c19067cae60cf909246
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - type: toggle
    device_id: 17ede8441b0d96619f9255122894377f
    entity_id: e273724e036742495ef4a2ebe8655158
    domain: light
  mode: single
- id: '1762140408973'
  alias: shower temp delay
  description: ''
  triggers:
  - device_id: 7230294486277129ba36ae06eee4748a
    domain: zha
    type: remote_button_short_press
    subtype: button
    trigger: device
  conditions: []
  actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 80
    target:
      area_id: bathroom
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 60
    target:
      area_id: bathroom
  mode: single
- id: '1762141277519'
  alias: Good Morning wakeup weekday
  description: ''
  triggers:
  - trigger: time
    at: 06:15:00
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
- id: '1762649853399'
  alias: Good morning weekenend
  description: ''
  triggers:
  - trigger: time
    at: 09:00:00
  conditions:
  - condition: time
    weekday:
    - sun
    - sat
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  - action: scene.turn_on
    metadata: {}
    data:
      transition: 900
    target:
      entity_id: scene.bedside_light_good_morning_post
  - delay:
      hours: 1
      minutes: 30
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 17ede8441b0d96619f9255122894377f
  mode: single
